[workspace]
resolver = "3"
members = [
    "crates/vash-core",
    "crates/vash-store",
    "crates/vash-proto",
    "crates/vash-server",
    "crates/vash-client",
    "crates/vash-bench",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.92"
license = "MIT OR Apache-2.0"
repository = "https://github.com/guichaguri/vash"

[workspace.dependencies]
vash-core = { path = "crates/vash-core" }
vash-store = { path = "crates/vash-store" }
vash-proto = { path = "crates/vash-proto" }
vash-client = { path = "crates/vash-client" }
vash-server = { path = "crates/vash-server" }

heed = "0.22.1"
tokio = { version = "1", features = ["rt-multi-thread", "net", "io-util", "macros", "signal", "sync", "time"] }
bytes = "1"
zerocopy = { version = "0.8", features = ["derive"] }
thiserror = "2"
anyhow = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
serde = { version = "1", features = ["derive"] }
toml = "0.9"
clap = { version = "4", features = ["derive"] }
xxhash-rust = { version = "0.8", features = ["xxh3"] }
crossbeam-channel = "0.5"
memchr = "2"
proptest = "1"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "abort"
debug = 1

[profile.bench]
lto = "thin"
codegen-units = 1


