[workspace]
resolver = "3"
members = [
    "crates/cache-core",
    "crates/cache-store",
    "crates/cache-proto",
    "crates/cache-server",
    "crates/cache-client",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.92"
license = "MIT OR Apache-2.0"
repository = "https://github.com/guichaguri/cache-server"

[workspace.dependencies]
cache-core = { path = "crates/cache-core" }
cache-store = { path = "crates/cache-store" }
cache-proto = { path = "crates/cache-proto" }
cache-client = { path = "crates/cache-client" }

heed = "0.22.1"
tokio = { version = "1", features = ["rt-multi-thread", "net", "io-util", "macros", "signal", "sync", "time"] }
bytes = "1"
zerocopy = { version = "0.8", features = ["derive"] }
thiserror = "2"
anyhow = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
serde = { version = "1", features = ["derive"] }
toml = "0.9"
clap = { version = "4", features = ["derive"] }
xxhash-rust = { version = "0.8", features = ["xxh3"] }
crossbeam-channel = "0.5"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "abort"
debug = 1

[profile.bench]
lto = "thin"
codegen-units = 1

