[package]
name = "cache-store"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
cache-core.workspace = true

bytes.workspace = true
crossbeam-channel.workspace = true
heed.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
tempfile = "3"

