[package]
name = "vash-proto"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
vash-core.workspace = true

bytes.workspace = true
memchr.workspace = true
thiserror.workspace = true
zerocopy.workspace = true

[dev-dependencies]
proptest.workspace = true

