[package]
name = "vash-bench"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
vash-core.workspace = true
vash-proto.workspace = true
vash-server.workspace = true

anyhow.workspace = true
bytes.workspace = true
tempfile = "3"
tokio.workspace = true

[dev-dependencies]
divan = "0.1"
vash-store.workspace = true
xxhash-rust.workspace = true

[[bench]]
name = "hot_path"
harness = false

[[bench]]
name = "write_path"
harness = false

[[bin]]
name = "load"
path = "src/load.rs"
