//! Authentication, over a real socket, in all three dialects.
//!
//! The test that matters most is [`no_vcp_opcode_executes_unauthenticated`]:
//! it enumerates the whole opcode space rather than the opcodes someone
//! remembered to list, so an opcode added later without a gate fails here
//! instead of shipping.

use std::net::SocketAddr;
use std::path::{Path, PathBuf};

use tempfile::TempDir;
use tokio::io::{AsyncReadExt, AsyncWriteExt};
use tokio::net::TcpStream;
use tokio::sync::oneshot;
use tokio::task::JoinHandle;
use vash_proto::vcp::{HEADER_LEN, Opcode, Status, encode_auth_body, encode_request};
use vash_server::{Config, Server};

const NAME: &str = "billing-api";

struct TestServer {
    addr: SocketAddr,
    _dir: TempDir,
    shutdown: Option<oneshot::Sender<()>>,
    handle: Option<JoinHandle<anyhow::Result<()>>>,
}

impl TestServer {
    /// Starts a server with one credential, enforced.
    async fn start() -> (Self, String) {
        Self::start_with(true, |_| {}).await
    }

    async fn start_with(required: bool, tweak: impl FnOnce(&mut Config)) -> (Self, String) {
        let dir = tempfile::tempdir().unwrap();
        let (secret, line) = vash_server::auth::generate(NAME).unwrap();
        let credentials = write_credentials(dir.path(), &line);

        let mut config = Config::default();
        config.server.listen = "127.0.0.1:0".parse().unwrap();
        config.store.path = dir.path().join("db");
        // The whole protocol suite runs against whichever engine this build
        // carries, so `--features mdbx` re-runs it on the second one. See
        // `crates/vash-store/tests/store.rs` for the same arrangement a layer
        // down, and `docs/mdbx-proposal.md` for why the choice is per build.
        #[cfg(feature = "mdbx")]
        {
            config.store.backend = vash_server::config::Backend::Mdbx;
        }
        config.store.map_size_mb = 64;
        // One LMDB environment rather than one per shard. Nothing here is about
        // sharding, and the suite runs in parallel against a finite pool of
        // thread-local slots — past it, `MDB_TLS_FULL`.
        config.store.shards = 1;
        config.observability.admin_listen = "127.0.0.1:0".into();
        config.auth.required = required;
        config.auth.file = credentials;
        tweak(&mut config);

        let server = Server::bind(config).await.expect("binding");
        let addr = server.local_addr().unwrap();
        let (tx, rx) = oneshot::channel();
        let handle = tokio::spawn(async move {
            server
                .serve(async {
                    let _ = rx.await;
                })
                .await
        });

        (
            Self {
                addr,
                _dir: dir,
                shutdown: Some(tx),
                handle: Some(handle),
            },
            secret,
        )
    }

    async fn connect(&self) -> Conn {
        let stream = TcpStream::connect(self.addr).await.expect("connecting");
        stream.set_nodelay(true).unwrap();
        Conn {
            stream,
            buf: Vec::new(),
        }
    }
}

impl Drop for TestServer {
    fn drop(&mut self) {
        drop(self.shutdown.take());
        self.handle.take();
    }
}

/// Writes a credential file the loader will accept.
///
/// The mode matters on Unix: the loader refuses a group- or world-readable
/// credential file the way `ssh` refuses a loose private key, and a temp file
/// is 0644 by default — so without this the whole suite would fail on CI and
/// pass on a Windows dev box.
fn write_credentials(dir: &Path, line: &str) -> PathBuf {
    let path = dir.join("credentials");
    std::fs::write(&path, format!("# generated by the test suite\n{line}\n")).unwrap();

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o600)).unwrap();
    }

    path
}

struct Conn {
    stream: TcpStream,
    buf: Vec<u8>,
}

impl Conn {
    async fn send(&mut self, bytes: &[u8]) {
        self.stream.write_all(bytes).await.expect("writing");
    }

    /// Sends one VCP frame and returns `(status, body)`.
    async fn vcp(&mut self, opcode: Opcode, body: &[u8]) -> (Status, Vec<u8>) {
        self.raw_vcp(opcode as u8, body).await
    }

    /// The same, for an opcode byte the encoder has no enum variant for — which
    /// is how [`no_vcp_opcode_executes_unauthenticated`] covers the bytes this
    /// build does not implement.
    async fn raw_vcp(&mut self, opcode: u8, body: &[u8]) -> (Status, Vec<u8>) {
        let mut frame = Vec::new();
        encode_request(&mut frame, Opcode::Ping, 7, body);
        frame[0] = opcode;
        self.send(&frame).await;

        self.fill(HEADER_LEN).await;
        let status = Status::from_u16(u16::from_le_bytes([self.buf[2], self.buf[3]]))
            .expect("a status this build knows");
        let body_len = u32::from_le_bytes(self.buf[8..12].try_into().unwrap()) as usize;
        assert_eq!(
            u32::from_le_bytes(self.buf[4..8].try_into().unwrap()),
            7,
            "the request id must be echoed"
        );

        self.fill(HEADER_LEN + body_len).await;
        let payload = self.buf[HEADER_LEN..HEADER_LEN + body_len].to_vec();
        self.buf.drain(..HEADER_LEN + body_len);
        (status, payload)
    }

    async fn hello(&mut self) -> u32 {
        let mut body = Vec::new();
        body.extend_from_slice(&1u16.to_le_bytes());
        body.extend_from_slice(&0u16.to_le_bytes());
        let (status, payload) = self.vcp(Opcode::Hello, &body).await;
        assert_eq!(status, Status::Ok, "HELLO must work before AUTH");
        u32::from_le_bytes(payload[12..16].try_into().unwrap())
    }

    async fn auth(&mut self, mechanism: u8, name: &str, secret: &str) -> Status {
        let mut body = Vec::new();
        encode_auth_body(&mut body, mechanism, name.as_bytes(), secret.as_bytes());
        self.vcp(Opcode::Auth, &body).await.0
    }

    async fn fill(&mut self, wanted: usize) {
        let mut chunk = [0u8; 8192];
        let deadline = tokio::time::Instant::now() + std::time::Duration::from_secs(5);
        while self.buf.len() < wanted {
            let read = tokio::time::timeout_at(deadline, self.stream.read(&mut chunk))
                .await
                .unwrap_or_else(|_| panic!("timed out waiting for {wanted} bytes"))
                .expect("reading");
            assert_ne!(read, 0, "server closed while a reply was outstanding");
            self.buf.extend_from_slice(&chunk[..read]);
        }
    }

    /// Reads text until it ends with `terminator`, for the two text dialects.
    async fn read_until(&mut self, terminator: &str) -> String {
        let mut chunk = [0u8; 8192];
        let deadline = tokio::time::Instant::now() + std::time::Duration::from_secs(5);
        loop {
            if let Ok(text) = std::str::from_utf8(&self.buf)
                && text.ends_with(terminator)
            {
                let out = text.to_string();
                self.buf.clear();
                return out;
            }
            let read = tokio::time::timeout_at(deadline, self.stream.read(&mut chunk))
                .await
                .unwrap_or_else(|_| {
                    panic!(
                        "timed out waiting for {terminator:?}; have {:?}",
                        String::from_utf8_lossy(&self.buf)
                    )
                })
                .expect("reading");
            assert_ne!(read, 0, "server closed while waiting for {terminator:?}");
            self.buf.extend_from_slice(&chunk[..read]);
        }
    }

    async fn text(&mut self, command: &str) -> String {
        self.send(command.as_bytes()).await;
        self.read_until("\r\n").await
    }
}

/// Builds a RESP request array.
fn resp(args: &[&str]) -> Vec<u8> {
    let mut out = format!("*{}\r\n", args.len()).into_bytes();
    for arg in args {
        out.extend_from_slice(format!("${}\r\n", arg.len()).as_bytes());
        out.extend_from_slice(arg.as_bytes());
        out.extend_from_slice(b"\r\n");
    }
    out
}

// ---- VCP -------------------------------------------------------------------

#[tokio::test]
async fn a_correct_credential_opens_the_connection() {
    let (server, secret) = TestServer::start().await;
    let mut conn = server.connect().await;

    conn.hello().await;
    assert_eq!(conn.auth(0, NAME, &secret).await, Status::Ok);
    assert_eq!(conn.vcp(Opcode::Ping, &[]).await.0, Status::Ok);
}

/// `HELLO` has to work before `AUTH` — first-byte detection requires a VCP
/// connection to open with it, so there is no way to authenticate first. The
/// capability bit is how a client discovers that it must.
#[tokio::test]
async fn hello_is_answered_before_auth_and_advertises_the_requirement() {
    let (server, _) = TestServer::start().await;
    let mut conn = server.connect().await;

    let capabilities = conn.hello().await;
    assert_ne!(
        capabilities & vash_core::capability::AUTH_REQUIRED,
        0,
        "a server that requires auth must say so in HELLO"
    );
}

#[tokio::test]
async fn the_capability_bit_is_clear_when_nothing_is_enforced() {
    let (server, _) = TestServer::start_with(false, |_| {}).await;
    let mut conn = server.connect().await;

    assert_eq!(
        conn.hello().await & vash_core::capability::AUTH_REQUIRED,
        0,
        "the bit reports enforcement, not that the build knows how"
    );
}

/// The whole opcode space, not a list someone maintained by hand: an opcode
/// added later without a gate has to fail here rather than ship.
#[tokio::test]
async fn no_vcp_opcode_executes_unauthenticated() {
    let (server, _) = TestServer::start().await;

    // The two that are legal before authenticating, each for a stated reason:
    // HELLO because the dialect must be announced first, AUTH because it is the
    // thing being announced.
    let pre_auth = [Opcode::Hello as u8, Opcode::Auth as u8];

    for byte in 0u8..=255 {
        if pre_auth.contains(&byte) {
            continue;
        }

        let mut conn = server.connect().await;
        conn.hello().await;
        let (status, body) = conn.raw_vcp(byte, b"whatever-body-this-opcode-wants").await;

        // Unknown and unimplemented opcodes included: answering `UNSUPPORTED`
        // to those would let an unauthenticated party enumerate which opcodes
        // this build has.
        assert_eq!(
            status,
            Status::Unauthorized,
            "opcode {byte:#04x} ({:?}) answered {status:?} unauthenticated",
            Opcode::from_u8(byte)
        );
        assert!(body.is_empty(), "opcode {byte:#04x} leaked a refusal body");
    }
}

/// `PING` looks harmless, but everything it could tell an unauthenticated party
/// `HELLO` already told them, and `/health` is the liveness check for an
/// operator.
#[tokio::test]
async fn ping_is_not_in_the_pre_auth_set() {
    let (server, _) = TestServer::start().await;
    let mut conn = server.connect().await;
    conn.hello().await;
    assert_eq!(conn.vcp(Opcode::Ping, &[]).await.0, Status::Unauthorized);
}

#[tokio::test]
async fn a_wrong_secret_and_an_unknown_name_are_both_refused() {
    let (server, secret) = TestServer::start().await;

    let mut conn = server.connect().await;
    conn.hello().await;
    assert_eq!(
        conn.auth(0, NAME, "not-the-secret").await,
        Status::Unauthorized
    );

    let mut conn = server.connect().await;
    conn.hello().await;
    assert_eq!(conn.auth(0, "nobody", &secret).await, Status::Unauthorized);
}

/// An empty name means the `default` identity, and this table has no such row.
#[tokio::test]
async fn an_empty_name_resolves_to_default() {
    let (server, secret) = TestServer::start().await;
    let mut conn = server.connect().await;
    conn.hello().await;
    assert_eq!(conn.auth(0, "", &secret).await, Status::Unauthorized);
}

/// Specified in docs/auth.md §6.3 and not built. `UNSUPPORTED` rather than
/// `UNAUTHORIZED`, so a client can probe for it and tell the two apart.
#[tokio::test]
async fn the_challenge_response_mechanism_reports_itself_unsupported() {
    let (server, secret) = TestServer::start().await;
    let mut conn = server.connect().await;
    conn.hello().await;

    assert_eq!(conn.auth(1, NAME, &secret).await, Status::Unsupported);
    assert_eq!(conn.auth(99, NAME, &secret).await, Status::Unsupported);
    // And the connection is still usable for a mechanism that does exist.
    assert_eq!(conn.auth(0, NAME, &secret).await, Status::Ok);
}

/// So a pooled connection can follow a rotation without reconnecting — and a
/// failed re-authentication is an attempt that did not land, not a logout.
#[tokio::test]
async fn re_authentication_replaces_the_identity_and_a_failure_does_not() {
    let (server, secret) = TestServer::start().await;
    let mut conn = server.connect().await;
    conn.hello().await;

    assert_eq!(conn.auth(0, NAME, &secret).await, Status::Ok);
    assert_eq!(conn.auth(0, NAME, "wrong").await, Status::Unauthorized);
    assert_eq!(
        conn.vcp(Opcode::Ping, &[]).await.0,
        Status::Ok,
        "a failed re-auth must not log the connection out"
    );
}

/// `NO_REPLY` suppresses a reply, and must not suppress the gate with it.
#[tokio::test]
async fn no_reply_cannot_smuggle_a_write_past_the_gate() {
    let (server, secret) = TestServer::start().await;
    let mut conn = server.connect().await;
    conn.hello().await;

    let mut set = Vec::new();
    vash_proto::vcp::encode_set_body(&mut set, b"smuggled", b"value", 0, &[]);
    let mut frame = Vec::new();
    encode_request(&mut frame, Opcode::Set, 1, &set);
    // Flip NO_REPLY on the built frame.
    frame[1] |= vash_proto::vcp::flags::NO_REPLY;
    conn.send(&frame).await;

    // Authenticate on the same connection, then look for the key. A gate that
    // only skipped the *reply* would have written it.
    assert_eq!(conn.auth(0, NAME, &secret).await, Status::Ok);
    assert_eq!(conn.vcp(Opcode::Get, b"smuggled").await.0, Status::NotFound);
}

/// An `AUTH` and the commands it authorises can arrive in a single read, so
/// authentication has to take effect within a block rather than between reads.
#[tokio::test]
async fn auth_takes_effect_inside_a_pipelined_block() {
    let (server, secret) = TestServer::start().await;
    let mut conn = server.connect().await;
    conn.hello().await;

    let mut batch = Vec::new();
    let mut auth_body = Vec::new();
    encode_auth_body(&mut auth_body, 0, NAME.as_bytes(), secret.as_bytes());
    encode_request(&mut batch, Opcode::Auth, 1, &auth_body);
    encode_request(&mut batch, Opcode::Ping, 2, &[]);
    conn.send(&batch).await;

    conn.fill(HEADER_LEN * 2).await;
    let first = Status::from_u16(u16::from_le_bytes([conn.buf[2], conn.buf[3]])).unwrap();
    let second = Status::from_u16(u16::from_le_bytes([
        conn.buf[HEADER_LEN + 2],
        conn.buf[HEADER_LEN + 3],
    ]))
    .unwrap();

    assert_eq!(first, Status::Ok);
    assert_eq!(
        second,
        Status::Ok,
        "the PING in the same read must see the AUTH before it"
    );
}

/// A twelve-byte header claiming a 64 MiB body would otherwise make the server
/// reserve 64 MiB for a connection that has presented nothing.
#[tokio::test]
async fn an_unauthenticated_connection_cannot_make_the_server_reserve() {
    let (server, _) = TestServer::start().await;
    let mut conn = server.connect().await;
    conn.hello().await;

    // A header only: the body it promises never arrives.
    let mut frame = Vec::new();
    encode_request(&mut frame, Opcode::Set, 1, &[]);
    frame[8..12].copy_from_slice(&(32 * 1024 * 1024u32).to_le_bytes());
    conn.send(&frame).await;

    let mut chunk = [0u8; 64];
    let read = tokio::time::timeout(
        std::time::Duration::from_secs(5),
        conn.stream.read(&mut chunk),
    )
    .await
    .expect("the server should have closed rather than reserved")
    .expect("reading");
    assert_eq!(read, 0, "expected a clean close, not a reservation");
}

/// The same bound over a text dialect, where the length is not in a header:
/// bytes simply accumulate until something parses.
#[tokio::test]
async fn an_unauthenticated_text_connection_cannot_fill_the_buffer() {
    let (server, _) = TestServer::start().await;
    let mut conn = server.connect().await;

    // A `get` line that never terminates. Every byte is a legal command byte,
    // so only the pre-auth budget stops it.
    conn.send(b"get ").await;
    conn.send(&vec![b'k'; 8192]).await;

    let mut chunk = [0u8; 64];
    let read = tokio::time::timeout(
        std::time::Duration::from_secs(5),
        conn.stream.read(&mut chunk),
    )
    .await
    .expect("the server should have closed")
    .expect("reading");
    assert_eq!(read, 0);
}

#[tokio::test]
async fn too_many_failures_close_the_connection() {
    let (server, _) = TestServer::start_with(true, |config| config.auth.max_attempts = 2).await;
    let mut conn = server.connect().await;
    conn.hello().await;

    assert_eq!(conn.auth(0, NAME, "wrong").await, Status::Unauthorized);
    // The second failure is answered, and *then* the socket goes: the client
    // learns why rather than seeing a bare disconnect.
    assert_eq!(conn.auth(0, NAME, "wrong").await, Status::Unauthorized);

    let mut chunk = [0u8; 64];
    let read = tokio::time::timeout(
        std::time::Duration::from_secs(5),
        conn.stream.read(&mut chunk),
    )
    .await
    .expect("the server should have closed the connection")
    .expect("reading");
    assert_eq!(read, 0, "expected a clean close after the attempt cap");
}

// ---- Rollout ---------------------------------------------------------------

/// Step one of the rollout: credentials configured, enforcement off. `AUTH` is
/// answered truthfully so clients can be rolled before the flag is flipped, and
/// nothing is refused in the meantime.
#[tokio::test]
async fn credentials_without_enforcement_refuse_nothing_but_still_answer_auth() {
    let (server, secret) = TestServer::start_with(false, |_| {}).await;
    let mut conn = server.connect().await;
    conn.hello().await;

    assert_eq!(
        conn.vcp(Opcode::Ping, &[]).await.0,
        Status::Ok,
        "nothing is enforced yet"
    );
    assert_eq!(conn.auth(0, NAME, &secret).await, Status::Ok);
    assert_eq!(
        conn.auth(0, NAME, "wrong").await,
        Status::Unauthorized,
        "a wrong credential is still wrong, enforced or not"
    );
}

// ---- Redis -----------------------------------------------------------------

#[tokio::test]
async fn redis_auth_in_both_forms() {
    let (server, secret) = TestServer::start().await;

    // Two arguments: the ACL form.
    let mut conn = server.connect().await;
    conn.send(&resp(&["AUTH", NAME, &secret])).await;
    assert_eq!(conn.read_until("\r\n").await, "+OK\r\n");
    conn.send(&resp(&["PING"])).await;
    assert_eq!(conn.read_until("\r\n").await, "+PONG\r\n");

    // One argument: Redis's pre-6 form, which means the `default` identity —
    // and this table has no `default` row.
    let mut conn = server.connect().await;
    conn.send(&resp(&["AUTH", &secret])).await;
    assert_eq!(
        conn.read_until("\r\n").await,
        "-WRONGPASS invalid username-password pair or user is disabled.\r\n"
    );
}

#[tokio::test]
async fn redis_refuses_commands_before_auth() {
    let (server, _) = TestServer::start().await;
    let mut conn = server.connect().await;

    conn.send(&resp(&["GET", "k"])).await;
    assert_eq!(
        conn.read_until("\r\n").await,
        "-NOAUTH Authentication required.\r\n"
    );

    // The introspection commands especially: one enumerates the keyspace and
    // the other describes the server, so they disclose more than a miss on a
    // key a stranger had to guess.
    for command in [&["SCAN", "0"][..], &["INFO"][..], &["INFO", "server"][..]] {
        conn.send(&resp(command)).await;
        assert_eq!(
            conn.read_until("\r\n").await,
            "-NOAUTH Authentication required.\r\n",
            "{command:?}"
        );
    }
}

/// Redis is *more* restrictive than VCP here, and deliberately: a bare `HELLO`
/// is refused with the message that explains the combined form.
#[tokio::test]
async fn redis_refuses_a_bare_hello_but_allows_the_combined_form() {
    let (server, secret) = TestServer::start().await;

    let mut conn = server.connect().await;
    conn.send(&resp(&["HELLO", "3"])).await;
    let reply = conn.read_until("\r\n").await;
    assert!(reply.starts_with("-NOAUTH HELLO must be called"), "{reply}");

    let mut conn = server.connect().await;
    conn.send(&resp(&["HELLO", "3", "AUTH", NAME, &secret]))
        .await;
    let reply = conn.read_until("\r\n").await;
    assert!(
        reply.starts_with("%7\r\n"),
        "expected a RESP3 map, got {reply}"
    );
}

/// A `HELLO 3 AUTH` with a bad credential must leave the connection exactly as
/// it was rather than switching it to RESP3 and then refusing.
#[tokio::test]
async fn a_failed_hello_auth_does_not_negotiate_resp3() {
    let (server, secret) = TestServer::start().await;
    let mut conn = server.connect().await;

    conn.send(&resp(&["HELLO", "3", "AUTH", NAME, "wrong"]))
        .await;
    assert_eq!(
        conn.read_until("\r\n").await,
        "-WRONGPASS invalid username-password pair or user is disabled.\r\n"
    );

    conn.send(&resp(&["AUTH", NAME, &secret])).await;
    assert_eq!(conn.read_until("\r\n").await, "+OK\r\n");
    conn.send(&resp(&["GET", "missing"])).await;
    assert_eq!(
        conn.read_until("\r\n").await,
        "$-1\r\n",
        "the connection must still be RESP2"
    );
}

#[tokio::test]
async fn redis_quit_works_before_auth() {
    let (server, _) = TestServer::start().await;
    let mut conn = server.connect().await;
    conn.send(&resp(&["QUIT"])).await;
    assert_eq!(conn.read_until("\r\n").await, "+OK\r\n");
}

/// Redis distinguishes "your credential is wrong" from "there is nothing here
/// to authenticate against", and a client must never have the two confused.
#[tokio::test]
async fn redis_says_so_when_no_credential_is_configured() {
    let dir = tempfile::tempdir().unwrap();
    let mut config = Config::default();
    config.server.listen = "127.0.0.1:0".parse().unwrap();
    config.store.path = dir.path().join("db");
    config.store.map_size_mb = 64;
    config.observability.admin_listen = "127.0.0.1:0".into();

    let server = Server::bind(config).await.unwrap();
    let addr = server.local_addr().unwrap();
    let (tx, rx) = oneshot::channel::<()>();
    let handle = tokio::spawn(async move {
        server
            .serve(async {
                let _ = rx.await;
            })
            .await
    });

    let stream = TcpStream::connect(addr).await.unwrap();
    let mut conn = Conn {
        stream,
        buf: Vec::new(),
    };
    conn.send(&resp(&["AUTH", "anything"])).await;
    assert_eq!(
        conn.read_until("\r\n").await,
        "-ERR AUTH <password> called without any password configured for the default user. \
         Are you sure your configuration is correct?\r\n"
    );

    drop(tx);
    let _ = handle.await;
}

// ---- Memcached -------------------------------------------------------------

/// Upstream's `-Y` ASCII authentication: credentials tunnelled through a `set`
/// whose key is the username and whose block is `<user> <pass>`.
#[tokio::test]
async fn memcached_ascii_auth() {
    let (server, secret) = TestServer::start().await;
    let mut conn = server.connect().await;

    let block = format!("{NAME} {secret}");
    let command = format!("set {NAME} 0 0 {}\r\n{block}\r\n", block.len());
    assert_eq!(conn.text(&command).await, "STORED\r\n");

    assert_eq!(conn.text("set k 0 0 1\r\nv\r\n").await, "STORED\r\n");
    assert_eq!(
        conn.get_value("get k\r\n").await,
        "VALUE k 0 1\r\nv\r\nEND\r\n"
    );
}

#[tokio::test]
async fn memcached_refuses_commands_before_auth() {
    let (server, _) = TestServer::start().await;
    let mut conn = server.connect().await;

    assert_eq!(
        conn.text("get k\r\n").await,
        "CLIENT_ERROR unauthenticated\r\n"
    );
    // A meta command too: the meta protocol has no auth command of its own, so
    // a meta-only client must send the classic `set` first.
    assert_eq!(
        conn.text("mg k v\r\n").await,
        "CLIENT_ERROR unauthenticated\r\n"
    );

    // And the introspection commands, which disclose the most: a keyspace dump
    // and the server's counters.
    for command in [
        "stats\r\n",
        "lru_crawler metadump all\r\n",
        "lru_crawler mgdump all\r\n",
    ] {
        assert_eq!(
            conn.text(command).await,
            "CLIENT_ERROR unauthenticated\r\n",
            "{command:?}"
        );
    }
}

/// The data block of a refused storage command must still be consumed, or every
/// command after it on the connection is read out of the middle of a value.
#[tokio::test]
async fn a_refused_storage_command_still_consumes_its_block() {
    let (server, secret) = TestServer::start().await;
    let mut conn = server.connect().await;

    // A `set` whose key is not a known identity: refused, block consumed.
    let block = format!("{NAME} {secret}");
    conn.send(
        format!(
            "set someone-else 0 0 5\r\nget k\r\nset {NAME} 0 0 {}\r\n{block}\r\n",
            block.len()
        )
        .as_bytes(),
    )
    .await;

    // Exactly two replies: the refusal, then the successful authentication. A
    // third would mean `get k\r\n` had been read as a command.
    //
    // The refusal is `authentication failure` rather than `unauthenticated`
    // because the block does split into a name and a secret — `get` and `k` —
    // which is an attempt naming an identity that does not exist. Upstream
    // answers the same for an unknown user.
    let replies = conn.read_until("STORED\r\n").await;
    assert_eq!(
        replies, "CLIENT_ERROR authentication failure\r\nSTORED\r\n",
        "the five-byte block was parsed as a command"
    );
}

/// Covered here rather than in the differential suite: upstream's answer to
/// this depends on whether the two commands land in one read, so it is not
/// something two servers can be compared on.
#[tokio::test]
async fn a_failed_memcached_attempt_does_not_authenticate() {
    let (server, _) = TestServer::start().await;
    let mut conn = server.connect().await;

    let block = format!("{NAME} not-the-secret");
    let command = format!("set {NAME} 0 0 {}\r\n{block}\r\n", block.len());
    assert_eq!(
        conn.text(&command).await,
        "CLIENT_ERROR authentication failure\r\n"
    );
    assert_eq!(
        conn.text("get k\r\n").await,
        "CLIENT_ERROR unauthenticated\r\n"
    );
}

/// A block that is not `<user> <pass>` is a malformed attempt, not an
/// unauthenticated command, and upstream distinguishes the two.
#[tokio::test]
async fn a_malformed_memcached_credential_says_so() {
    let (server, secret) = TestServer::start().await;
    let mut conn = server.connect().await;

    let command = format!("set {NAME} 0 0 {}\r\n{secret}\r\n", secret.len());
    assert_eq!(
        conn.text(&command).await,
        "CLIENT_ERROR bad authentication token format\r\n"
    );
}

/// An unparseable command from an unauthenticated connection is answered as an
/// unauthenticated one, so a stranger cannot probe which verbs exist.
#[tokio::test]
async fn an_unknown_memcached_command_is_refused_as_unauthenticated() {
    let (server, _) = TestServer::start().await;
    let mut conn = server.connect().await;

    assert_eq!(
        conn.text("frobnicate\r\n").await,
        "CLIENT_ERROR unauthenticated\r\n"
    );
    // A malformed *storage* command, whose data block still has to be sent and
    // consumed — the byte count is readable even though the flags are not.
    assert_eq!(
        conn.text("set broken notanumber 0 1\r\nx\r\n").await,
        "CLIENT_ERROR unauthenticated\r\n"
    );
}

#[tokio::test]
async fn memcached_quit_works_before_auth() {
    let (server, _) = TestServer::start().await;
    let mut conn = server.connect().await;

    conn.send(b"quit\r\n").await;
    let mut chunk = [0u8; 16];
    let read = tokio::time::timeout(
        std::time::Duration::from_secs(5),
        conn.stream.read(&mut chunk),
    )
    .await
    .expect("quit should close the connection")
    .unwrap();
    assert_eq!(read, 0);
}

impl Conn {
    async fn get_value(&mut self, command: &str) -> String {
        self.send(command.as_bytes()).await;
        self.read_until("END\r\n").await
    }
}

// ---- Configuration ---------------------------------------------------------

/// The foot-gun this whole feature is most likely to trip: peers are ordinary
/// VCP clients on the ordinary port, so auth without a peer credential breaks
/// invalidation cluster-wide *while every node reports itself healthy*.
/// Refusing to start is the only failure mode an operator cannot miss.
#[test]
fn a_clustered_node_without_a_peer_credential_refuses_to_start() {
    let mut config = Config::default();
    config.auth.required = true;
    config.auth.file = PathBuf::from("/nonexistent/credentials");
    config.cluster.peers = vec!["127.0.0.1:11312".into()];

    let error = format!("{:#}", config.validate().unwrap_err());
    assert!(error.contains("cluster.auth_secret"), "{error}");

    config.cluster.auth_secret = "a-secret-long-enough".into();
    assert!(config.validate().is_ok());
}

/// Enforcement with an empty table locks out every client including the node's
/// own peers.
#[tokio::test]
async fn enforcement_without_credentials_refuses_to_start() {
    let dir = tempfile::tempdir().unwrap();
    let mut config = Config::default();
    config.server.listen = "127.0.0.1:0".parse().unwrap();
    config.store.path = dir.path().join("db");
    config.store.map_size_mb = 64;
    config.observability.admin_listen = "127.0.0.1:0".into();
    config.auth.required = true;

    let Err(error) = Server::bind(config).await else {
        panic!("a server with auth required and no credentials must not start");
    };
    let error = format!("{error:#}");
    assert!(error.contains("no credentials are configured"), "{error}");
}
